# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('account_name', models.CharField(max_length=30)),
                ('account_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sKey', models.CharField(max_length=40, verbose_name='Secret Key')),
                ('iKey', models.CharField(max_length=20, verbose_name='Integration Key')),
                ('name', models.CharField(max_length=30)),
                ('api_hostname', models.CharField(max_length=8, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duos.Account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_phone', models.CharField(max_length=11)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duos.Application')),
            ],
        ),
    ]
